version: "3.8"

services:
  rspec:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    working_dir: /app
    stdin_open: true
    tty: true
    command: /bin/bash

volumes:
  bundle_cache:
